### ISSUE TITLE
Some Abilities appear as "None"

### ISSUE THREAD

**Issue by ArchOwlen** [roguedex-dev/roguedex#20]
Overgrow (grass starter ability) is not shown in the UI

Looking at the code, it seems every ability is manually inserted into background.js

Wouldn't there be a way to detect the ability from PokeRogue directly so it would be more future-proof? 

(Unless this is chrome-specific that it needs to be listed)

![image](https://github.com/roguedex-dev/roguedex/assets/69368336/e5b05685-3245-495b-9690-c5bd6a52185b)

**Comment by ArchOwlen** [comment]
![image](https://github.com/roguedex-dev/roguedex/assets/69368336/ab0903ff-a3c9-4619-a5bc-8c0886b5b8eb)

**Comment by Baiscj** [comment]
The only ability that would show for me is Stench. Otherwise it just show none.

**Comment by roguedex-dev** [comment]
the "Abilities" enum comes straight from Pokerogue code which you can see here:
https://github.com/pagefaultgames/pokerogue/blob/main/src/data/enums/abilities.ts

I guess we could add pokerogue as a submodule of this repo, and then use symlinks to always fetch the latest version of the file, however this does not seem to be the issue here. I guess that starter abilities are just in a different category than "abilities", which is what I'm currently showing. I'll look into it as a bug

**Comment by AntonioCheca** [comment]
I think I have backtracked the bug. Roguedex is right now reading the overall Abilities enum but internally what is being saved is just the local ability of each Pokemon (usually 0 or 1 because pokemons usually only have 2 abilities, that's why most of what people can see now is None and Stench).

The way pokerogue handles that can be seen in this file in the pokerogue repository: https://github.com/pagefaultgames/pokerogue/blob/main/src/data/pokemon-species.ts where they create each pokemon species with all the abilities each one has. 

It would be needed to just cross-reference that 0 or 1 with the array on that file. The issue is that this is dependent on the other objects, so maybe the submodule idea would solve that. Another idea would be to create the array temporarily just by regexing that file, which is what I would do because I don't expect the types to change often.

Another issue would be fused Pokemon abilities.

**Comment by roguedex-dev** [comment]
Thanks for this work, I had investigated this already and came to the same conclusion, as I'm usually working alone I didn't think of putting my findings in this thread :D, sorry for making you waste your time.

I also have an idea of how to do that, which is pretty much cleaning up those constructor calls and creating an enum out of it where the value is an array.

Also, that helps with the tooltip about what an abilities does, because you can just convert the ability name to lower case camel case and fetch the description from i18n.

About fused pokemon, I think I've seen a formula somewhere in code a couple of days ago on how the resulting ability is calculated, which we could pretty much just copy paste

**Comment by roguedex-dev** [comment]
Solved with latest version
